# Generated by Django 4.2.13 on 2026-07-07 19:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('open_class', 'Clase Abierta / Puertas Abiertas'), ('individual', 'Visita Individual')], default='individual', max_length=20, verbose_name='Tipo de visita')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Cupo')),
                ('location', models.CharField(blank=True, default='Campus Interlaken', max_length=200, verbose_name='Ubicación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('google_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidad',
                'ordering': ['date', 'start_time'],
                'unique_together': {('visit_type', 'date', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=200, verbose_name='Nombre del padre/tutor')),
                ('parent_email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='Teléfono / WhatsApp')),
                ('child_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del alumno')),
                ('child_grade', models.CharField(blank=True, max_length=50, verbose_name='Grado de interés')),
                ('num_attendees', models.PositiveIntegerField(default=1, verbose_name='Número de asistentes')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('attended', 'Asistió'), ('no_show', 'No asistió')], default='confirmed', max_length=20)),
                ('source', models.CharField(choices=[('web', 'Sitio web'), ('whatsapp', 'WhatsApp'), ('admin', 'Administración')], default='web', max_length=20)),
                ('google_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.availabilityslot')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
    ]
