# Generated by Django 6.1 on 2026-08-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_reminder_sent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['is_active', 'date'], name='bookings_av_is_acti_a16610_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['visit_type', 'is_active', 'date'], name='bookings_av_visit_t_10781e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['slot', 'status'], name='bookings_bo_slot_id_b05dec_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', '-created_at'], name='bookings_bo_status_eb4fb1_idx'),
        ),
    ]
