# Generated by Django 6.1 on 2026-08-23 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_availabilityslot_bookings_av_is_acti_a16610_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='outcome',
            field=models.CharField(blank=True, choices=[('', 'Sin registrar'), ('interested', 'Interesada, dar seguimiento'), ('enrolling', 'Se inscribirá'), ('not_now', 'No por ahora'), ('declined', 'No le interesó')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='outcome_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bookings.availabilityslot'),
        ),
    ]
