[pytest]
DJANGO_SETTINGS_MODULE = config.settings.development
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts = -ra -q
testpaths = apps
filterwarnings =
    ignore::DeprecationWarning:factory.django
    ignore:.*STATICFILES_STORAGE setting is deprecated.*:
    ignore:.*Pagination may yield inconsistent results.*:
