# Generated by Django 6.1.1 on 2026-09-25 02:59, then hand-extended with the
# Postgres-only trigram indexes (Data Ops Phase 1).

from django.conf import settings
from django.db import migrations, models

# Auditoría searches ``context`` / ``actor_label`` with ``icontains``, which
# Postgres compiles to ``UPPER(col) LIKE UPPER(%s)``: a sequential scan over the
# largest table in the database (3 rows per POS purchase, never purged). A GIN
# trigram index on the same ``UPPER(col)`` expression makes that LIKE indexable.
# Guarded: SQLite has no GIN; the extension comes from 0004_pg_extensions.
TRIGRAM_INDEXES = (
    ('core_audit_context_trgm', 'context'),
    ('core_audit_actor_trgm', 'actor_label'),
)


def create_trigram_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    table = apps.get_model('core', 'AuditLog')._meta.db_table
    quote = schema_editor.quote_name
    with schema_editor.connection.cursor() as cursor:
        for name, column in TRIGRAM_INDEXES:
            cursor.execute(
                f'CREATE INDEX IF NOT EXISTS {quote(name)} ON {quote(table)} '
                f'USING gin (UPPER({quote(column)}) gin_trgm_ops)'
            )


def drop_trigram_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    quote = schema_editor.quote_name
    with schema_editor.connection.cursor() as cursor:
        for name, _ in TRIGRAM_INDEXES:
            cursor.execute(f'DROP INDEX IF EXISTS {quote(name)}')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pg_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_trigram_indexes, drop_trigram_indexes),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Creación'), ('update', 'Modificación'), ('delete', 'Eliminación'), ('permission', 'Cambio de permisos'), ('export', 'Exportación'), ('import', 'Importación')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='core_audit_action_created'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['is_handled', '-created_at'], name='core_contact_handled_created'),
        ),
    ]
