# Generated by Django 4.2.13 on 2026-07-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_display', models.CharField(blank=True, default='(55) 1234-5678', help_text='Como se muestra en pantalla, p. ej. “(55) 1234-5678”. Vacío = se oculta el teléfono.', max_length=50, verbose_name='Teléfono (texto visible)')),
                ('phone_e164', models.CharField(blank=True, default='+525512345678', help_text='Formato internacional para enlaces tel:, p. ej. +525512345678.', max_length=25, verbose_name='Teléfono (marcado)')),
                ('whatsapp_number', models.CharField(blank=True, default='5215512345678', help_text='Solo dígitos con lada de país, p. ej. 5215512345678 (se usa en enlaces wa.me). Vacío = se ocultan los botones de WhatsApp.', max_length=20, verbose_name='WhatsApp')),
                ('contact_email', models.EmailField(blank=True, default='colegio@interlaken.edu.mx', max_length=254, verbose_name='Correo de contacto')),
                ('address', models.CharField(blank=True, default='Tlalnepantla de Baz, Estado de México', max_length=200, verbose_name='Dirección')),
                ('maps_url', models.URLField(blank=True, default='https://maps.google.com/?q=Tlalnepantla+de+Baz', verbose_name='Enlace de Google Maps')),
                ('office_hours', models.CharField(blank=True, default='Lunes–Viernes 8:00–16:00 hrs', max_length=100, verbose_name='Horario de oficina')),
                ('facebook_url', models.URLField(blank=True, default='', verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, default='', verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, default='', verbose_name='YouTube')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ajustes del sitio',
                'verbose_name_plural': 'Ajustes del sitio',
            },
        ),
    ]
