# Generated by Django 4.2.13 on 2026-07-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_real_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, default='Av. de los Reyes 67, Residencial el Dorado, Tlalnepantla, Estado de México', max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://www.facebook.com/colegiointerlaken', verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maps_url',
            field=models.URLField(blank=True, default='https://maps.app.goo.gl/Xd241Sht8TmrMHUe6', verbose_name='Enlace de Google Maps'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_display',
            field=models.CharField(blank=True, default='(55) 5379-1188', help_text='Como se muestra en pantalla, p. ej. “(55) 5379-1188”. Vacío = se oculta el teléfono.', max_length=50, verbose_name='Teléfono (texto visible)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_e164',
            field=models.CharField(blank=True, default='+525553791188', help_text='Formato internacional para enlaces tel:, p. ej. +525553791188.', max_length=25, verbose_name='Teléfono (marcado)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='5215553791188', help_text='Solo dígitos con lada de país, p. ej. 5215553791188 (se usa en enlaces wa.me). Vacío = se ocultan los botones de WhatsApp.', max_length=20, verbose_name='WhatsApp'),
        ),
    ]
