# Generated by Django 4.2.13 on 2026-07-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_real_contact_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=60, verbose_name='Sección')),
                ('inscripcion', models.DecimalField(blank=True, decimal_places=2, help_text='Vacío = se muestra "SIN COSTO".', max_digits=8, null=True, verbose_name='Inscripción / reinscripción (MXN)')),
                ('colegiatura', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Colegiatura mensual (MXN)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible en el sitio')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Costo por sección',
                'verbose_name_plural': 'Costos por sección',
                'ordering': ['order', 'id'],
            },
        ),
    ]
