# Generated by Django 6.1 on 2026-08-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_seed_tuition_costs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaycareRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible en el sitio')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.CharField(max_length=60, verbose_name='Horario')),
                ('service', models.CharField(max_length=120, verbose_name='Servicio')),
                ('daily_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo diario (MXN)')),
                ('monthly_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Vacío = sin tarifa mensual (p. ej. multa).', max_digits=8, null=True, verbose_name='Costo mensual (MXN)')),
                ('monthly_note', models.CharField(blank=True, default='', help_text='Texto mostrado en lugar (o además) del costo mensual.', max_length=120, verbose_name='Nota de mensualidad')),
            ],
            options={
                'verbose_name': 'Tarifa de estancia',
                'verbose_name_plural': 'Estancia',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtracurricularActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible en el sitio')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='Clase')),
                ('levels', models.CharField(max_length=120, verbose_name='Niveles')),
                ('annual_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Anualidad (MXN)')),
            ],
            options={
                'verbose_name': 'Extraescolar',
                'verbose_name_plural': 'Extraescolares',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FixedConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible en el sitio')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='Concepto')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo (MXN)')),
                ('mandatory', models.BooleanField(default=True, verbose_name='Obligatorio')),
            ],
            options={
                'verbose_name': 'Seguro / credencial',
                'verbose_name_plural': 'Seguros y credenciales',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PricingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible en el sitio')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Política')),
            ],
            options={
                'verbose_name': 'Política de precios',
                'verbose_name_plural': 'Políticas de precios',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnrollmentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible en el sitio')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(max_length=60, verbose_name='Sección')),
                ('modality', models.CharField(choices=[('nuevo_ingreso', 'Nuevo ingreso'), ('reinscripcion', 'Reinscripción (alumnos Interlaken)')], max_length=20, verbose_name='Modalidad')),
                ('gastos_administrativos', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Gastos administrativos (MXN)')),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cuota de inscripción (MXN)')),
            ],
            options={
                'verbose_name': 'Cuota de inscripción',
                'verbose_name_plural': 'Cuotas de inscripción',
                'ordering': ['order', 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('section', 'modality'), name='uniq_enrollment_section_modality')],
            },
        ),
    ]
