# Generated by Django 6.1 on 2026-08-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_seed_pricing_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='URL de YouTube o Vimeo. Vacío = la sección no se muestra en el sitio.', verbose_name='Video institucional'),
        ),
    ]
