# Generated by Django 6.1 on 2026-08-15 15:31, then extended with a guarded
# data migration (school-confirmed activations, 2026-08-15):
#  - video_url: set the official institutional video ONLY if still empty, so a
#    future admin edit is never clobbered by a redeploy.
#  - contact_email: the real monitored mailboxes live on interlaken.com.mx
#    (per-level directory, legal notice, admin accounts); .edu.mx is the web
#    domain only (GO-LIVE-AUDIT #19). Update the row ONLY if it still holds the
#    old code default.
from django.db import migrations, models

OFFICIAL_VIDEO_URL = 'https://youtu.be/z271WfIaPSE'
OLD_EMAIL_DEFAULT = 'colegio@interlaken.edu.mx'
NEW_EMAIL_DEFAULT = 'colegio@interlaken.com.mx'


def apply_activations(apps, schema_editor):
    SiteSettings = apps.get_model('content', 'SiteSettings')
    row = SiteSettings.objects.filter(pk=1).first()
    if row is None:
        return
    changed = False
    if not row.video_url:
        row.video_url = OFFICIAL_VIDEO_URL
        changed = True
    if row.contact_email == OLD_EMAIL_DEFAULT:
        row.contact_email = NEW_EMAIL_DEFAULT
        changed = True
    if changed:
        row.save(update_fields=['video_url', 'contact_email', 'updated_at'])


def revert_activations(apps, schema_editor):
    SiteSettings = apps.get_model('content', 'SiteSettings')
    row = SiteSettings.objects.filter(pk=1).first()
    if row is None:
        return
    changed = False
    if row.video_url == OFFICIAL_VIDEO_URL:
        row.video_url = ''
        changed = True
    if row.contact_email == NEW_EMAIL_DEFAULT:
        row.contact_email = OLD_EMAIL_DEFAULT
        changed = True
    if changed:
        row.save(update_fields=['video_url', 'contact_email', 'updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_sitesettings_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='colegio@interlaken.com.mx', max_length=254, verbose_name='Correo de contacto'),
        ),
        migrations.RunPython(apply_activations, revert_activations),
    ]
