# Generated by Django 6.1 on 2026-08-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_sitesettings_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='info@interlaken.com.mx', max_length=254, verbose_name='Correo de contacto'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='office_hours',
            field=models.CharField(blank=True, default='Lunes a Viernes 7:30 - 15:00', max_length=100, verbose_name='Horario de oficina'),
        ),
    ]
