# Generated by Django 6.1 on 2026-08-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_apply_contact_email_and_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video_url',
            field=models.URLField(blank=True, default='', help_text='URL directa a un MP4/WebM corto (≤ 15 s, sin audio). Vacío = imagen fija.', verbose_name='Video del hero (MP4/WebM)'),
        ),
    ]
