# Generated by Django 6.1 on 2026-08-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_hero_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Título')),
                ('kind', models.CharField(choices=[('holiday', 'Suspensión de clases'), ('vacation', 'Vacaciones'), ('exam', 'Evaluaciones'), ('event', 'Evento escolar'), ('meeting', 'Junta de padres'), ('deadline', 'Fecha límite')], default='event', max_length=12, verbose_name='Tipo')),
                ('start_date', models.DateField(verbose_name='Inicio')),
                ('end_date', models.DateField(blank=True, help_text='Vacío = un solo día.', null=True, verbose_name='Fin')),
                ('level', models.CharField(blank=True, help_text="Vacío = todos; o 'preescolar' / 'primaria' / 'secundaria'.", max_length=12, verbose_name='Nivel')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descripción')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento del calendario',
                'verbose_name_plural': 'Calendario escolar',
                'ordering': ['start_date', 'title'],
            },
        ),
    ]
