# Generated by Django 6.1 on 2026-08-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_school_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(max_length=400, verbose_name='Testimonio')),
                ('author', models.CharField(max_length=120, verbose_name='Nombre')),
                ('role', models.CharField(blank=True, help_text='Ej. "Mamá de alumno de 3° de primaria" o "Egresado 2019".', max_length=120, verbose_name='Relación')),
                ('level', models.CharField(blank=True, max_length=12, verbose_name='Nivel')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
