# Generated by Django 6.1 on 2026-08-22 21:53

import apps.content.media
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_testimonial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.content.media._upload_to)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=80)),
                ('size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Pie de foto')),
                ('focal_x', models.FloatField(default=0.5)),
                ('focal_y', models.FloatField(default=0.5)),
                ('tags', models.CharField(blank=True, help_text='Separadas por coma', max_length=200)),
                ('variants', models.JSONField(blank=True, default=dict)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen (CMS)',
                'verbose_name_plural': 'Biblioteca de medios',
                'ordering': ['-created_at'],
            },
        ),
    ]
