# Generated by Django 6.1 on 2026-08-22 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_media_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('template', models.CharField(choices=[('home', 'Inicio'), ('level', 'Nivel educativo'), ('simple', 'Página simple'), ('landing', 'Landing')], default='simple', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada')], db_index=True, default='draft', max_length=10)),
                ('draft_blocks', models.JSONField(blank=True, default=list)),
                ('seo', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página (CMS)',
                'verbose_name_plural': 'Páginas (CMS)',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('blocks', models.JSONField(default=list)),
                ('seo', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content.page')),
            ],
            options={
                'ordering': ['-number'],
                'unique_together': {('page', 'number')},
            },
        ),
        migrations.AddField(
            model_name='page',
            name='published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.pageversion'),
        ),
    ]
