# Generated by Django 6.1 on 2026-08-22 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_cms_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('fields', models.JSONField(default=list)),
                ('consent_text', models.CharField(blank=True, default='He leído el Aviso de Privacidad y acepto el tratamiento de mis datos.', max_length=300)),
                ('notify_to', models.EmailField(blank=True, help_text='Buzón que recibe cada envío (vacío = CONTACT_EMAIL).', max_length=254)),
                ('success_message', models.CharField(default='Gracias. Le responderemos en menos de 2 días hábiles.', max_length=300)),
                ('submit_label', models.CharField(default='Enviar', max_length=40)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('page', models.CharField(blank=True, help_text='Ruta desde la que se envió', max_length=120)),
                ('is_handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='content.formdefinition')),
            ],
            options={
                'verbose_name': 'Envío de formulario',
                'verbose_name_plural': 'Envíos de formularios',
                'ordering': ['-created_at'],
            },
        ),
    ]
