# Generated by Django 6.1 on 2026-08-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_cms_forms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_path', models.CharField(help_text='Ruta antigua, p. ej. /inscripciones', max_length=200, unique=True)),
                ('to_path', models.CharField(help_text='Ruta nueva o URL completa', max_length=500)),
                ('permanent', models.BooleanField(default=True, help_text='301 (permanente) o 302 (temporal)')),
                ('hits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Redirección',
                'verbose_name_plural': 'Redirecciones',
                'ordering': ['from_path'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu',
            field=models.JSONField(blank=True, default=list, verbose_name='Menú del sitio'),
        ),
    ]
