# Generated by Django 6.1 on 2026-08-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sep_incorporations',
            field=models.JSONField(blank=True, default=list, help_text='[{level, label}] tal como aparece en el documento oficial. Vacío = valores integrados.', verbose_name='Incorporaciones SEP'),
        ),
    ]
