# Generated by Django 6.1 on 2026-08-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_page_review_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='last_rollover_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='school_year',
            field=models.CharField(blank=True, help_text='AAAA-AAAA', max_length=9, verbose_name='Ciclo escolar'),
        ),
    ]
