# Generated by Django 6.1 on 2026-08-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tpl_missing_docs',
            field=models.TextField(blank=True, default='', verbose_name='Plantilla: documentos faltantes'),
        ),
    ]
