# Generated by Django 6.1.1 on 2026-09-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_seed_institutional_video'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form', 'is_handled', '-created_at'], name='content_formsub_handled'),
        ),
    ]
