# Generated by Django 6.1.1 on 2026-09-26 04:27

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Fill ``search_text`` for existing rows (same rule as FormSubmission.save)."""
    from apps.content.forms import build_search_text

    FormSubmission = apps.get_model('content', 'FormSubmission')
    batch = []
    for sub in FormSubmission.objects.only('pk', 'data', 'page').iterator(chunk_size=500):
        sub.search_text = build_search_text(sub.data, sub.page)
        batch.append(sub)
        if len(batch) >= 500:
            FormSubmission.objects.bulk_update(batch, ['search_text'])
            batch = []
    if batch:
        FormSubmission.objects.bulk_update(batch, ['search_text'])


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_data_ops_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='search_text',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
