from django.urls import path

from .forms import (
    FormBulkView,
    FormDetailView,
    FormExportView,
    FormListCreateView,
    FormSubmissionBulkView,
    FormSubmissionDetailView,
    FormSubmissionsExportView,
    FormSubmissionsView,
    PublicFormSubmitView,
    PublicFormView,
)
from .media import (
    MediaBulkView,
    MediaDetailView,
    MediaExportView,
    MediaListCreateView,
    MediaServeView,
)
from .navigation import (
    AdminRedirectDetailView,
    AdminRedirectsBulkView,
    AdminRedirectsExportView,
    AdminRedirectsImportTemplateView,
    AdminRedirectsImportView,
    AdminRedirectsView,
    PublicRedirectsView,
    RedirectHitView,
)
from .pages import (
    PageBulkView,
    PageChecksView,
    PageDetailView,
    PageExportView,
    PageListCreateView,
    PagePreviewByTokenView,
    PagePreviewTokenView,
    PagePreviewView,
    PagePublishView,
    PageReviewView,
    PageVersionsView,
    PublicPageView,
)
from .views import (
    AdminCalendarBulkView,
    AdminCalendarDetailView,
    AdminCalendarExportView,
    AdminCalendarImportTemplateView,
    AdminCalendarImportView,
    AdminCalendarView,
    AdminSiteSettingsView,
    AdminTestimonialDetailView,
    AdminTestimonialsBulkView,
    AdminTestimonialsExportView,
    AdminTestimonialsView,
    PublicCalendarIcsView,
    PublicCalendarView,
    PublicPricingView,
    PublicSiteSettingsView,
    PublicTestimonialsView,
    PublicTuitionCostsView,
)

urlpatterns = [
    path('settings/', PublicSiteSettingsView.as_view(), name='site-settings'),
    path('costs/', PublicTuitionCostsView.as_view(), name='tuition-costs'),
    path('pricing/', PublicPricingView.as_view(), name='pricing-bundle'),
    path('admin/settings/', AdminSiteSettingsView.as_view(), name='admin-site-settings'),
    path('calendar/', PublicCalendarView.as_view(), name='school-calendar'),
    path('calendar.ics', PublicCalendarIcsView.as_view(), name='school-calendar-ics'),
    path('testimonials/', PublicTestimonialsView.as_view(), name='testimonials'),
    path('media/<int:pk>/<str:variant>/', MediaServeView.as_view(), name='media-serve'),
    path('pages/preview/', PagePreviewByTokenView.as_view(), name='cms-page-preview-token'),
    path('pages/<slug:slug>/', PublicPageView.as_view(), name='cms-page'),
    path('pages/<int:pk>/preview/', PagePreviewView.as_view(), name='cms-page-preview'),
    path('admin/pages/', PageListCreateView.as_view(), name='admin-pages'),
    path('admin/pages/export/', PageExportView.as_view(), name='admin-pages-export'),
    path('admin/pages/bulk/', PageBulkView.as_view(), name='admin-pages-bulk'),
    path('admin/pages/<int:pk>/', PageDetailView.as_view(), name='admin-page-detail'),
    path('admin/pages/<int:pk>/publish/', PagePublishView.as_view(), name='admin-page-publish'),
    path('admin/pages/<int:pk>/versions/', PageVersionsView.as_view(), name='admin-page-versions'),
    path('admin/pages/<int:pk>/preview-token/', PagePreviewTokenView.as_view(), name='admin-page-preview-token'),
    path('admin/pages/<int:pk>/checks/', PageChecksView.as_view(), name='admin-page-checks'),
    path('admin/pages/<int:pk>/review/', PageReviewView.as_view(), name='admin-page-review'),
    path('redirects/', PublicRedirectsView.as_view(), name='cms-redirects'),
    path('redirects/hit/', RedirectHitView.as_view(), name='cms-redirect-hit'),
    path('admin/redirects/', AdminRedirectsView.as_view(), name='admin-redirects'),
    path('admin/redirects/export/', AdminRedirectsExportView.as_view(), name='admin-redirects-export'),
    path('admin/redirects/bulk/', AdminRedirectsBulkView.as_view(), name='admin-redirects-bulk'),
    path('admin/redirects/import/', AdminRedirectsImportView.as_view(), name='admin-redirects-import'),
    path('admin/redirects/import/template/', AdminRedirectsImportTemplateView.as_view(), name='admin-redirects-import-template'),
    path('admin/redirects/<int:pk>/', AdminRedirectDetailView.as_view(), name='admin-redirect-detail'),
    path('forms/<slug:slug>/', PublicFormView.as_view(), name='cms-form'),
    path('forms/<slug:slug>/submit/', PublicFormSubmitView.as_view(), name='cms-form-submit'),
    path('admin/forms/', FormListCreateView.as_view(), name='admin-forms'),
    path('admin/forms/export/', FormExportView.as_view(), name='admin-forms-export'),
    path('admin/forms/bulk/', FormBulkView.as_view(), name='admin-forms-bulk'),
    path('admin/forms/<int:pk>/', FormDetailView.as_view(), name='admin-form-detail'),
    path('admin/forms/<int:pk>/submissions/', FormSubmissionsView.as_view(), name='admin-form-submissions'),
    path('admin/forms/<int:pk>/submissions/export/', FormSubmissionsExportView.as_view(), name='admin-form-submissions-export'),
    path('admin/form-submissions/bulk/', FormSubmissionBulkView.as_view(), name='admin-form-submissions-bulk'),
    path('admin/form-submissions/<int:pk>/', FormSubmissionDetailView.as_view(), name='admin-form-submission-detail'),
    path('admin/media/', MediaListCreateView.as_view(), name='admin-media'),
    path('admin/media/export/', MediaExportView.as_view(), name='admin-media-export'),
    path('admin/media/bulk/', MediaBulkView.as_view(), name='admin-media-bulk'),
    path('admin/media/<int:pk>/', MediaDetailView.as_view(), name='admin-media-detail'),
    path('admin/testimonials/', AdminTestimonialsView.as_view(), name='admin-testimonials'),
    path('admin/testimonials/export/', AdminTestimonialsExportView.as_view(), name='admin-testimonials-export'),
    path('admin/testimonials/bulk/', AdminTestimonialsBulkView.as_view(), name='admin-testimonials-bulk'),
    path('admin/testimonials/<int:pk>/', AdminTestimonialDetailView.as_view(), name='admin-testimonial-detail'),
    path('admin/calendar/', AdminCalendarView.as_view(), name='admin-calendar'),
    path('admin/calendar/export/', AdminCalendarExportView.as_view(), name='admin-calendar-export'),
    path('admin/calendar/bulk/', AdminCalendarBulkView.as_view(), name='admin-calendar-bulk'),
    path('admin/calendar/import/', AdminCalendarImportView.as_view(), name='admin-calendar-import'),
    path('admin/calendar/import/template/', AdminCalendarImportTemplateView.as_view(), name='admin-calendar-import-template'),
    path('admin/calendar/<int:pk>/', AdminCalendarDetailView.as_view(), name='admin-calendar-detail'),
]
