# Generated by Django 4.2.13 on 2026-07-07 05:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('online', 'Pago en Línea'), ('office', 'Caja Escolar')], default='office', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('payment_ref', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_requests', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Solicitud de Recarga',
                'verbose_name_plural': 'Solicitudes de Recarga',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CafeteriaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Compra'), ('topup', 'Recarga'), ('refund', 'Devolución')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('loyverse_receipt_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafeteria_transactions', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Transacción de Cafetería',
                'verbose_name_plural': 'Transacciones de Cafetería',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CafeteriaBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('low_balance_threshold', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cafeteria_balance', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Saldo de Cafetería',
            },
        ),
    ]
