# Generated by Django 4.2.13 on 2026-07-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteriabalance',
            name='last_low_balance_alert_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
