# Generated by Django 4.2.13 on 2026-07-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_cafeteriabalance_last_low_balance_alert_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteriatransaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cafeteriatransaction',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
