# Generated by Django 4.2.13 on 2026-07-08 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('cafeteria', '0003_cafeteriatransaction_balance_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeteriatransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Compra'), ('topup', 'Recarga'), ('refund', 'Devolución'), ('adjustment', 'Ajuste')], max_length=20),
        ),
        migrations.CreateModel(
            name='BalanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('adjustment', 'Ajuste manual'), ('refund', 'Devolución')], default='adjustment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafeteria_adjustments', to=settings.AUTH_USER_MODEL)),
                ('source_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='cafeteria.cafeteriatransaction')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_adjustments', to='accounts.studentprofile')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='cafeteria.cafeteriatransaction')),
            ],
            options={
                'verbose_name': 'Ajuste de Saldo',
                'verbose_name_plural': 'Ajustes de Saldo',
                'ordering': ['-created_at'],
            },
        ),
    ]
