# Generated by Django 4.2.13 on 2026-07-13 04:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cafeteria', '0004_alter_cafeteriatransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyverseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyverse_id', models.CharField(db_index=True, max_length=100, verbose_name='ID de Loyverse')),
                ('customer_code', models.CharField(blank=True, max_length=40, verbose_name='Matrícula (Loyverse)')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nombre en Loyverse')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('phone_number', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
                ('address_code', models.CharField(blank=True, max_length=40, verbose_name='Código de grado (address)')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('first_visit', models.DateTimeField(blank=True, null=True, verbose_name='Primera visita')),
                ('last_visit', models.DateTimeField(blank=True, null=True, verbose_name='Última visita')),
                ('total_visits', models.PositiveIntegerField(default=0, verbose_name='Visitas')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gasto total')),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Puntos / saldo')),
                ('loyverse_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Alta en Loyverse')),
                ('loyverse_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Última actualización (Loyverse)')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Datos completos (Loyverse)')),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sincronizado')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyverse_profile', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Perfil de Loyverse',
                'verbose_name_plural': 'Perfiles de Loyverse',
                'ordering': ['-last_visit'],
            },
        ),
    ]
