# Generated by Django 4.2.13 on 2026-07-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0005_loyverseprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyverseSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_full_fetch_at', models.DateTimeField(blank=True, null=True, verbose_name='Última descarga completa')),
            ],
            options={
                'verbose_name': 'Estado de sincronización Loyverse',
                'verbose_name_plural': 'Estado de sincronización Loyverse',
            },
        ),
    ]
