# Generated by Django 4.2.13 on 2026-08-01 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cafeteria', '0006_loyversesyncstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceadjustment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_adjustments', to='accounts.studentprofile'),
        ),
        migrations.AlterField(
            model_name='cafeteriabalance',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cafeteria_balance', to='accounts.studentprofile'),
        ),
        migrations.AlterField(
            model_name='cafeteriatransaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cafeteria_transactions', to='accounts.studentprofile'),
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topup_requests', to='accounts.studentprofile'),
        ),
    ]
