# Generated by Django 4.2.13 on 2026-08-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0007_alter_balanceadjustment_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteriabalance',
            name='daily_spend_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='cafeteriabalance',
            name='last_budget_alert_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafeteriabalance',
            name='weekly_spend_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
