# Generated by Django 4.2.13 on 2026-08-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0008_cafeteriabalance_daily_spend_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyversesyncstate',
            name='last_purchases_cursor',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cursor de compras (poll)'),
        ),
    ]
