# Generated by Django 4.2.13 on 2026-08-12 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0009_loyversesyncstate_last_purchases_cursor'),
        ('cafeteria', '0009_topuprequest_pos_unload'),
    ]

    operations = [
    ]
