# Generated by Django 6.1 on 2026-08-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_accounts_st_loyvers_3b117d_idx_and_more'),
        ('cafeteria', '0010_merge_20260811_2306'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cafeteriatransaction',
            index=models.Index(fields=['student', '-date'], name='cafeteria_c_student_d6f136_idx'),
        ),
        migrations.AddIndex(
            model_name='cafeteriatransaction',
            index=models.Index(fields=['transaction_type', 'date'], name='cafeteria_c_transac_daa0d5_idx'),
        ),
    ]
