# Generated by Django 6.1.1 on 2026-09-23 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_studentprofile_loyverse_missing_since'),
        ('cafeteria', '0013_loyversesyncstate_last_poll_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmatchedReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('customer_id', models.CharField(db_index=True, max_length=100)),
                ('receipt_date', models.DateTimeField(blank=True, null=True)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Recibo sin alumno',
                'verbose_name_plural': 'Recibos sin alumno',
                'ordering': ['-seen_at'],
            },
        ),
        migrations.AddField(
            model_name='cafeteriabalance',
            name='seeded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafeteriatransaction',
            name='recorded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='cafeteriatransaction',
            index=models.Index(fields=['student', '-recorded_at'], name='cafeteria_c_student_16bbba_idx'),
        ),
        migrations.AddField(
            model_name='unmatchedreceipt',
            name='resolved_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replayed_receipts', to='accounts.studentprofile'),
        ),
    ]
