# Generated by Django 6.1.1 on 2026-09-23 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_studentprofile_loyverse_missing_since'),
        ('cafeteria', '0014_convergence_recorded_at_seeded_at_unmatchedreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyverseprofile',
            name='kind',
            field=models.CharField(choices=[('student', 'Alumno'), ('staff', 'Personal'), ('test', 'Prueba'), ('other', 'Otro')], db_index=True, default='other', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='loyverseprofile',
            name='missing_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ausente en Loyverse desde'),
        ),
        migrations.AlterField(
            model_name='loyverseprofile',
            name='loyverse_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='ID de Loyverse'),
        ),
        migrations.AlterField(
            model_name='loyverseprofile',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyverse_profile', to='accounts.studentprofile'),
        ),
    ]
