# Generated by Django 6.1.1 on 2026-09-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0015_loyverseprofile_every_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteriatransaction',
            name='applied',
            field=models.BooleanField(default=True),
        ),
    ]
