# Generated by Django 6.1.1 on 2026-09-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0016_cafeteriatransaction_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyverseprofile',
            name='applied_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre aplicado al roster'),
        ),
        migrations.AddField(
            model_name='loyversesyncstate',
            name='last_roster_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última sincronización del roster'),
        ),
    ]
