# Generated by Django 6.1.1 on 2026-09-25 03:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_studentprofile_loyverse_missing_since'),
        # Stacked on Phase 0 (fix/loyverse-roster-sync) so cafeteria keeps a single leaf.
        ('cafeteria', '0017_loyversesyncstate_last_roster_sync_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafeteriabalance',
            options={'ordering': ['student__user__last_name', 'student__user__first_name', 'pk'], 'verbose_name': 'Saldo de Cafetería'},
        ),
        migrations.AddIndex(
            model_name='balanceadjustment',
            index=models.Index(fields=['created_at'], name='caf_adjustment_created'),
        ),
        migrations.AddIndex(
            model_name='cafeteriatransaction',
            index=models.Index(fields=['date'], name='caf_tx_date'),
        ),
        migrations.AddIndex(
            model_name='loyverseprofile',
            index=models.Index(fields=['customer_code'], name='caf_loyprofile_code'),
        ),
        migrations.AddIndex(
            model_name='topuprequest',
            index=models.Index(fields=['status', '-created_at'], name='caf_topup_status_created'),
        ),
        migrations.AddIndex(
            model_name='unmatchedreceipt',
            index=models.Index(fields=['resolved_at'], name='caf_unmatched_resolved'),
        ),
        migrations.AddConstraint(
            model_name='topuprequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='caf_topup_amount_positive'),
        ),
    ]
