# Generated by Django 4.2.13 on 2026-07-08 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_payment_related_topup_alter_payment_gateway'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('level', models.CharField(blank=True, help_text='Preescolar / Primaria / Secundaria (informativo).', max_length=30)),
                ('grade', models.CharField(blank=True, help_text='Grado exacto (ej. "3° Primaria"). Vacío = regla predeterminada para toda la escuela.', max_length=20)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('due_day', models.PositiveSmallIntegerField(default=5, help_text='Día del mes en que vence la colegiatura (1-28).')),
                ('late_fee_type', models.CharField(choices=[('none', 'Sin recargo'), ('fixed', 'Monto fijo (MXN)'), ('percent', 'Porcentaje (%)')], default='none', max_length=10)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_fee_grace_days', models.PositiveSmallIntegerField(default=0, help_text='Días de gracia tras el vencimiento antes del recargo.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de Colegiatura',
                'verbose_name_plural': 'Planes de Colegiatura',
                'ordering': ['-active', 'grade', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Periodo de facturación YYYY-MM.', max_length=7)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField()),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_fee_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada')], default='pending', max_length=12)),
                ('late_fee_applied', models.BooleanField(default=False)),
                ('reminder_before_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_overdue_sent_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finance.feeschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Colegiatura (Factura)',
                'verbose_name_plural': 'Colegiaturas (Facturas)',
                'ordering': ['-period', 'student'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payments', to='finance.invoice')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payment', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Pago de Colegiatura',
                'verbose_name_plural': 'Pagos de Colegiatura',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tuition', 'Colegiatura'), ('discount', 'Descuento'), ('late_fee', 'Recargo por mora'), ('adjustment', 'Ajuste')], default='tuition', max_length=12)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.invoice')),
            ],
            options={
                'verbose_name': 'Concepto de Factura',
                'verbose_name_plural': 'Conceptos de Factura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mark_paid', 'Marcada como pagada'), ('adjust', 'Ajuste de monto'), ('cancel', 'Cancelación'), ('discount', 'Descuento manual')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reason', models.TextField()),
                ('status_after', models.CharField(blank=True, max_length=12)),
                ('amount_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_paid_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_adjustments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='finance.invoice')),
            ],
            options={
                'verbose_name': 'Ajuste de Factura',
                'verbose_name_plural': 'Ajustes de Factura',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('sibling', 'Descuento por hermanos'), ('family', 'Descuento familiar'), ('scholarship', 'Beca'), ('other', 'Otro')], default='other', max_length=20)),
                ('method', models.CharField(choices=[('percent', 'Porcentaje (%)'), ('fixed', 'Monto fijo (MXN)')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('start_period', models.CharField(blank=True, help_text='YYYY-MM (inclusive).', max_length=7)),
                ('end_period', models.CharField(blank=True, help_text='YYYY-MM (inclusive).', max_length=7)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_discounts', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Descuento / Beca',
                'verbose_name_plural': 'Descuentos / Becas',
                'ordering': ['student', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='finance_inv_status_0e2dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['period'], name='finance_inv_period_035203_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('student', 'period'), name='uniq_invoice_student_period'),
        ),
    ]
