# Generated by Django 4.2.13 on 2026-07-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
