# Generated by Django 4.2.13 on 2026-08-01 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('finance', '0002_invoicepayment_applied_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.studentprofile'),
        ),
    ]
