# Generated by Django 4.2.13 on 2026-08-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_invoice_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceadjustment',
            name='kind',
            field=models.CharField(
                choices=[
                    ('mark_paid', 'Marcada como pagada'),
                    ('adjust', 'Ajuste de monto'),
                    ('cancel', 'Cancelación'),
                    ('discount', 'Descuento manual'),
                    ('refund', 'Devolución'),
                ],
                max_length=12,
            ),
        ),
    ]
