# Generated by Django 6.1 on 2026-08-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_accounts_st_loyvers_3b117d_idx_and_more'),
        ('finance', '0004_invoiceadjustment_refund_kind'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'late_fee_applied'], name='finance_inv_status_4d056c_idx'),
        ),
    ]
