# Generated by Django 6.1 on 2026-08-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_password_reset_and_notif_prefs'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['loyverse_id'], name='accounts_st_loyvers_3b117d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['is_active', 'loyverse_id'], name='accounts_st_is_acti_b8b0c0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
    ]
