# Generated by Django 6.1 on 2026-08-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_accounts_st_loyvers_3b117d_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
