# Generated by Django 6.1 on 2026-08-22 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_drop_password_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_email', models.EmailField(blank=True, max_length=254)),
                ('requester_name', models.CharField(blank=True, max_length=150)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Correo'), ('phone', 'Teléfono'), ('in_person', 'Presencial')], default='whatsapp', max_length=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('open', 'Pendiente'), ('resolved', 'Resuelta'), ('rejected', 'Rechazada')], db_index=True, default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_via', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('email', 'Correo'), ('phone', 'Teléfono'), ('in_person', 'Presencial')], max_length=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de contraseña',
                'verbose_name_plural': 'Solicitudes de contraseña',
                'ordering': ['-created_at'],
            },
        ),
    ]
