# Generated by Django 6.1 on 2026-08-22 18:07

from django.db import migrations, models


def backfill(apps, schema_editor):
    StudentProfile = apps.get_model('accounts', 'StudentProfile')
    StudentProfile.objects.filter(is_active=False).update(status='withdrawn')



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_password_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('on_leave', 'Baja temporal'), ('graduated', 'Egresado'), ('withdrawn', 'Baja definitiva')], db_index=True, default='active', max_length=12),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
