# Generated by Django 6.1 on 2026-08-22 18:32

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='allergies',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='blood_type',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='curp',
            field=models.CharField(blank=True, max_length=20, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_rel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='medical_notes',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
    ]
