# Generated by Django 6.1 on 2026-08-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_studentprofile_extended'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='cat_cafeteria',
            field=models.BooleanField(default=True, verbose_name='Cafetería'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='cat_info',
            field=models.BooleanField(default=True, verbose_name='Comunicados y avisos'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='cat_payment',
            field=models.BooleanField(default=True, verbose_name='Pagos'),
        ),
    ]
