# Generated by Django 6.1 on 2026-08-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notif_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_file',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
