# Generated by Django 6.1 on 2026-08-23 00:10

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_avatar_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=254)),
                ('method', models.CharField(choices=[('password', 'Contraseña'), ('google', 'Google')], max_length=10)),
                ('success', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=40)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inicio de sesión',
                'verbose_name_plural': 'Historial de inicios de sesión',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TotpDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', apps.core.fields.EncryptedTextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Segundo factor (TOTP)',
                'verbose_name_plural': 'Segundos factores (TOTP)',
            },
        ),
    ]
