# Generated by Django 6.1 on 2026-08-23 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_security'),
        ('admissions', '0008_document_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to='admissions.registration'),
        ),
    ]
