# Generated by Django 6.1 on 2026-08-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_admissions_pipeline'),
        ('admissions', '0008_document_review_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['grade', 'group'], name='accounts_st_grade_c17b7d_idx'),
        ),
    ]
