# Generated by Django 6.1.1 on 2026-09-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_student_grade_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='loyverse_missing_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
