# Generated by Django 6.1 on 2026-08-15 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_announcement_fanout_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', 'audience', '-created_at'], name='portal_anno_is_acti_038a89_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='portal_noti_user_id_0da583_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['delivered_at', 'created_at'], name='portal_noti_deliver_51d3b2_idx'),
        ),
    ]
