# Generated by Django 6.1 on 2026-08-15 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_announcement_portal_anno_is_acti_038a89_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='push_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='portal.announcement'),
        ),
    ]
