# Generated by Django 6.1 on 2026-08-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_announcement_push_enabled_notification_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('skipped', 'Omitido'), ('failed', 'Falló')], default='pending', max_length=8),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_error',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('skipped', 'Omitido'), ('failed', 'Falló')], default='pending', max_length=8),
        ),
    ]
