# Generated by Django 6.1 on 2026-08-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_notification_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='show_on_site',
            field=models.BooleanField(default=False, verbose_name='Publicar en el sitio'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='site_link',
            field=models.CharField(blank=True, max_length=300, verbose_name='Enlace del aviso'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='site_until',
            field=models.DateField(blank=True, null=True, verbose_name='Mostrar en el sitio hasta'),
        ),
    ]
