# Generated by Django 6.1 on 2026-08-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_site_notices'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='announcement',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Vacío = al guardar. Mientras no llegue la hora, el comunicado es un borrador programado.', null=True, verbose_name='Publicar el'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='requires_ack',
            field=models.BooleanField(default=False, verbose_name='Requiere enterado'),
        ),
        migrations.AddField(
            model_name='announcementread',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
