# Generated by Django 4.2.13 on 2026-07-07 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('tuition', 'Colegiatura'), ('enrollment', 'Inscripción'), ('cafeteria', 'Recarga Cafetería'), ('other', 'Otro')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('success', 'Exitoso'), ('failed', 'Fallido'), ('refunded', 'Devuelto')], default='pending', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('gateway', models.CharField(default='global_payments', max_length=50)),
                ('gateway_tx_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('gateway_ref', models.CharField(blank=True, max_length=255)),
                ('gateway_raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
