# Generated by Django 4.2.13 on 2026-07-07 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0003_cafeteriatransaction_balance_after_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='related_topup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cafeteria.topuprequest'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('global_payments', 'Global Payments'), ('banorte', 'Banorte')], default='global_payments', max_length=50),
        ),
    ]
