# Generated by Django 6.1.1 on 2026-09-25 02:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Payment's FK to TopUpRequest predates 0017; depending on 0016 keeps this
        # migration independent of the two parallel cafeteria 0017 leaves
        # (Data Ops Phase 1 indexes and Phase 0 roster-sync state).
        ('cafeteria', '0016_cafeteriatransaction_applied'),
        ('payments', '0004_retire_tuition_enrollment_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='pay_payment_created'),
        ),
    ]
