# Generated by Django 4.2.13 on 2026-07-08 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyNoticeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(default='Aviso de Privacidad', max_length=200)),
                ('body', models.TextField(verbose_name='Texto del aviso')),
                ('integral_notice_url', models.URLField(blank=True, default='', verbose_name='URL del aviso integral')),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=False, verbose_name='Vigente')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Versión del aviso de privacidad',
                'verbose_name_plural': 'Versiones del aviso de privacidad',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('academic_processing', 'Tratamiento académico'), ('cafeteria', 'Cafetería'), ('photos_media', 'Fotografías y medios'), ('communications_marketing', 'Comunicaciones y marketing'), ('medical_data', 'Datos de salud')], max_length=40)),
                ('granted', models.BooleanField()),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('capture_context', models.CharField(blank=True, default='', max_length=80)),
                ('capture_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
                ('notice_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='legal.privacynoticeversion')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Registro de consentimiento',
                'verbose_name_plural': 'Registros de consentimiento',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['guardian', 'purpose', 'captured_at'], name='legal_conse_guardia_a40f80_idx'), models.Index(fields=['student', 'purpose', 'captured_at'], name='legal_conse_student_9c8f2e_idx')],
            },
        ),
    ]
