# Generated by Django 4.2.13 on 2026-07-08 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_email', models.EmailField(max_length=254)),
                ('request_type', models.CharField(choices=[('access', 'Acceso'), ('rectification', 'Rectificación'), ('cancellation', 'Cancelación'), ('opposition', 'Oposición')], max_length=20)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('received', 'Recibida'), ('in_review', 'En revisión'), ('resolved', 'Resuelta'), ('rejected', 'Rechazada')], default='received', max_length=20)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('statutory_deadline', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arco_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud ARCO',
                'verbose_name_plural': 'Solicitudes ARCO',
                'ordering': ['-created_at'],
            },
        ),
    ]
