# Generated by Django 6.1 on 2026-08-23 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0005_aviso_remove_legacy_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arcorequest',
            name='channel',
            field=models.CharField(choices=[('portal', 'Portal'), ('email', 'Correo (privacidad@)'), ('whatsapp', 'WhatsApp'), ('in_person', 'Presencial')], default='portal', max_length=12),
        ),
        migrations.AddField(
            model_name='arcorequest',
            name='intake_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arcorequest',
            name='requester_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
