# Generated by Django 6.1.1 on 2026-09-25 02:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0006_arco_intake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='arcorequest',
            index=models.Index(fields=['status', '-created_at'], name='legal_arco_status_created'),
        ),
    ]
