# Generated by Django 4.2.13 on 2026-07-07 05:05

import apps.admissions.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSchoolDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Fecha del evento')),
                ('event_time', models.CharField(max_length=20, verbose_name='Horario')),
                ('event_name', models.CharField(default='Puertas Abiertas', max_length=200, verbose_name='Nombre del evento')),
                ('max_capacity', models.PositiveIntegerField(default=30)),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=20)),
                ('child_name', models.CharField(blank=True, max_length=200)),
                ('child_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('level_interest', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('attended', 'Asistió')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Puertas Abiertas',
                'verbose_name_plural': 'Puertas Abiertas',
                'ordering': ['event_date', 'event_time'],
            },
        ),
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_first_name', models.CharField(max_length=100, verbose_name='Nombre del alumno')),
                ('child_last_name', models.CharField(max_length=100, verbose_name='Apellidos del alumno')),
                ('child_dob', models.DateField(verbose_name='Fecha de nacimiento')),
                ('level', models.CharField(choices=[('preescolar', 'Preescolar'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=20, verbose_name='Nivel educativo')),
                ('grade_applying', models.CharField(max_length=30, verbose_name='Grado a solicitar')),
                ('cycle', models.CharField(default='2025-2026', max_length=20, verbose_name='Ciclo escolar')),
                ('parent_name', models.CharField(max_length=200, verbose_name='Nombre del padre/tutor')),
                ('parent_email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='Teléfono / WhatsApp')),
                ('relationship', models.CharField(default='Padre/Madre', max_length=50, verbose_name='Parentesco')),
                ('referral_source', models.CharField(blank=True, max_length=100, verbose_name='¿Cómo nos conoció?')),
                ('message', models.TextField(blank=True, verbose_name='Comentarios adicionales')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('contacted', 'Contactado'), ('enrolled', 'Inscrito'), ('rejected', 'No Procedió')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
            ],
            options={
                'verbose_name': 'Pre-registro',
                'verbose_name_plural': 'Pre-registros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_first_name', models.CharField(max_length=100)),
                ('child_last_name', models.CharField(max_length=100)),
                ('child_dob', models.DateField()),
                ('child_curp', models.CharField(blank=True, max_length=20, verbose_name='CURP')),
                ('child_nationality', models.CharField(default='Mexicana', max_length=50)),
                ('level', models.CharField(max_length=20)),
                ('grade_applying', models.CharField(max_length=30)),
                ('cycle', models.CharField(default='2025-2026', max_length=20)),
                ('parent1_name', models.CharField(max_length=200)),
                ('parent1_email', models.EmailField(max_length=254)),
                ('parent1_phone', models.CharField(max_length=20)),
                ('parent1_occupation', models.CharField(blank=True, max_length=100)),
                ('parent2_name', models.CharField(blank=True, max_length=200)),
                ('parent2_email', models.EmailField(blank=True, max_length=254)),
                ('parent2_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_name', models.CharField(blank=True, max_length=200)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_rel', models.CharField(blank=True, max_length=50)),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('medical_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviado'), ('reviewing', 'En Revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('complete', 'Inscripción Completa')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('pre_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='admissions.preregistration')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('birth_cert', 'Acta de Nacimiento'), ('curp_doc', 'CURP'), ('photo', 'Fotografía'), ('report_card', 'Boleta Anterior'), ('proof_addr', 'Comprobante de Domicilio'), ('vaccination', 'Cartilla de Vacunación'), ('other', 'Otro Documento')], max_length=30)),
                ('file', models.FileField(upload_to=apps.admissions.models.document_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_verified', models.BooleanField(default=False)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.registration')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
