# Generated by Django 4.2.13 on 2026-07-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
        ('admissions', '0003_registration_invite_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='consent_medical_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='consent_photos_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='privacy_notice_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='legal.privacynoticeversion'),
        ),
    ]
