# Generated by Django 4.2.13 on 2026-07-08 18:09

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_registration_consent_medical_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='estatura',
            field=apps.core.fields.EncryptedTextField(blank=True, default='', verbose_name='Estatura'),
        ),
        migrations.AddField(
            model_name='registration',
            name='peso',
            field=apps.core.fields.EncryptedTextField(blank=True, default='', verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='allergies',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='registration',
            name='blood_type',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='registration',
            name='medical_notes',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
    ]
