# Generated by Django 4.2.13 on 2026-08-09 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_registration_estatura_registration_peso_and_more'),
        # Ensure the historical port from OpenSchoolDay → AvailabilitySlot
        # (bookings.0002) has run before the legacy table is dropped.
        ('bookings', '0002_openclass_unification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenSchoolDay',
        ),
    ]
