# Generated by Django 6.1 on 2026-08-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_delete_openschoolday'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='wants_visit',
            field=models.BooleanField(default=False, verbose_name='Desea agendar visita'),
        ),
    ]
