# Generated by Django 6.1 on 2026-08-22 20:38

from django.db import migrations, models


def backfill(apps, schema_editor):
    Doc = apps.get_model('admissions', 'RegistrationDocument')
    Doc.objects.filter(is_verified=True).update(status='approved')



class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_preregistration_wants_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdocument',
            name='review_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='registrationdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=10),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
