# Generated by Django 6.1.1 on 2026-09-25 02:59

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_document_review_status'),
        ('legal', '0007_data_ops_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='preregistration',
            index=models.Index(fields=['status', '-created_at'], name='adm_prereg_status_created'),
        ),
        migrations.AddIndex(
            model_name='preregistration',
            index=models.Index(django.db.models.functions.text.Lower('parent_email'), name='adm_prereg_email_lower'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['status', '-updated_at'], name='adm_reg_status_updated'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['status', '-created_at'], name='adm_reg_status_created'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(django.db.models.functions.text.Lower('parent1_email'), name='adm_reg_p1email_lower'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(django.db.models.functions.text.Lower('parent2_email'), name='adm_reg_p2email_lower'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['child_curp'], name='adm_reg_child_curp'),
        ),
    ]
