# Generated by Django 6.1.1 on 2026-09-26 02:04

import apps.admissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_data_ops_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistration',
            name='cycle',
            field=models.CharField(default=apps.admissions.models.current_school_cycle, max_length=20, verbose_name='Ciclo escolar'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='cycle',
            field=models.CharField(default=apps.admissions.models.current_school_cycle, max_length=20),
        ),
    ]
